### ISSUE TITLE
Where is the code for the Image Feature Alignment?

### ISSUE THREAD

**Issue by blessingforever** [zlai0/MAST#16]
Thanks for your amazing work. In the Implementation Details of your paper, you describe an approach for the Image Feature Alignment, which I would like to try. Could you please indicate the location of it in your code or give more details about it?

**Comment by eugene87222** [comment]
According to the second question in #1, it seems to be at line 43 in `models/colorizer.py` ([here](https://github.com/zlai0/MAST/blob/a57b043ca597b9b7ef6842b1fa965c9f1ee71526/models/colorizer.py#L43))

**Comment by zlai0** [comment]
That is correct.
