### ISSUE TITLE
Question about  Lab channel dropout

### ISSUE THREAD

**Issue by liyz15** [zlai0/MAST#19]
https://github.com/zlai0/MAST/blob/a57b043ca597b9b7ef6842b1fa965c9f1ee71526/models/mast.py#L43-L44

This is essentially

```
drop_ch_num = 1
drop_ch_ind = [np.random.choice([1, 2])]
```

In the paper all three channels of Lab are decorrelated. Is it on purpose that `L` channel is preserved?

Great work! Thanks in advance.

**Comment by zlai0** [comment]
Hey sorry for the confusion. The paper actually says "One of the color channels is randomly dropped with probability p=0.5". Here in the context of Lab colour space, the colour channels typically refer to only _ab_, whereas the L channel is referred to as the _lightness channel_, which does not contain colour information. However I must say this line could be misinterpreted.

I looked at my original code and did find another version (i.e. all three channels could be dropped), but I forgot what the specific performance was. I assume the current version yields better performance..

**Comment by liyz15** [comment]
Thanks for the clarification!
