### ISSUE TITLE
Code release scheduled date?

### ISSUE THREAD

**Issue by miriaford** [zlai0/MAST#3]
Hi, 

I'm really inspired by your work, and would love to check out the code! It's been 4 months since your initial commit. When do you plan to open-source? 

Thank you so much!

**Comment by wenbinTse** [comment]
I'm so disappointed.  Another work of this author, [corrflow](https://github.com/zlai0/CorrFlow), is also nonreproducible.

**Comment by miriaford** [comment]
@zlai0 because you committed to open-sourcing, could you please at least give us an estimated time?

**Comment by WeidiXie** [comment]
> I'm so disappointed. Another work of this author, [corrflow](https://github.com/zlai0/CorrFlow), is also nonreproducible.

May I know which part is non-reproducible ?  you mean the pre-trained weights are not working ?

**Comment by miriaford** [comment]
Bumping up this thread
