### ISSUE TITLE
Issues about RGB 2 lab space

### ISSUE THREAD

**Issue by carrierlxk** [zlai0/MAST#7]
Thanks for sharing codes. When I run the training code, I find an issue as follow:
YTVOSTrainLoader.py", line 28, in lab_preprocess
image = cv2.cvtColor(image, cv2.COLOR_BGR2Lab)
cv2.error: OpenCV(4.3.0) /io/opencv/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<3>; VDepth = cv::impl::{anonymous}::Set<0, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

I think it may be raised by converting grayscale images to color space.  Can you provide some solutions?

**Comment by upxinxin** [comment]
hello, i met the same problem .Have you solved the problem? If i worked, could you give me some advice? Thanks a lot!

**Comment by carrierlxk** [comment]
Because some images in the dataset are not existing.

**Comment by BWYWTB** [comment]
> Because some images in the dataset are not existing.

Have you solved the problem? I tried but failed. Thanks!

**Comment by InnovArul** [comment]
Hi, How did you overcome this issue? 
I mean, did you find out why the images are not existing? or did you skip the non-existing images?

Could you pl. let me know this.

**Comment by upxinxin** [comment]
> Hi, How did you overcome this issue?
> I mean, did you find out why the images are not existing? or did you skip the non-existing images?
> 
> Could you pl. let me know this.

Hi , i skipped the no-existing images and it worked.

**Comment by InnovArul** [comment]
Thanks for your reply. I did the same.

**Comment by Sora-dw** [comment]
> Thanks for your reply. I did the same.

hello! I meet the same question, too. And I am wondering how to skip the non-existing images like you said. By the way, which database do you use?
